# Generated by Django 6.1.1 on 2026-09-20 10:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("taxi", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="car",
            name="drivers",
            field=models.ManyToManyField(
                related_name="drivers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
